apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yoonglory/common-logs
    targetRevision: HEAD
    path: my-python-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

