apiVersion: v1
kind: Service
metadata:
  name: pyapp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: pyapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}

