name: Build & Push to ECR

on:
  push:
    paths:
      - 'app.py'
      - 'Dockerfile'
    branches: [ main ]

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 이 권한이 필요합니다!

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set version
      id: vars
      run: echo "VERSION=v1.0.${{ github.run_number }}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image to ECR
      run: |
        IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO }}
        docker build -t $IMAGE:$VERSION .
        docker push $IMAGE:$VERSION

    - name: Update image tag in Helm values.yaml
      run: |
        sed -i "s|tag: .*|tag: \"$VERSION\"|" my-python-app/values.yaml

    - name: Commit and push updated values.yaml
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "${{ secrets.GIT_USER_NAME }}"
        git config user.email "${{ secrets.GIT_USER_EMAIL }}"
        git add my-python-app/values.yaml
        git commit -m "Update Helm image tag to $VERSION" || echo "No changes"

        git push https://x-access-token:${{secrets.GH_PAT}}@github.com/${{ github.repository }}.git HEAD:main

